source = $HOME/.config/hypr/theme.conf

general {
	hide_cursor = true
	ignore_empty_layout = true
	fail_timeout = 300
}
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldWidth, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
}
background {
	monitor = 
	path = /home/forest-terminal/wal/nuke.png
	color = $muted
	blur_passes = 0
	blur_size = 2
	noise = 0.03
}
input-field {
	monitor = 
	size = 500 , 60
	dots_size = 0.2
	dots_spacing = 0.2
	outer_color = rgba(0,0,0,0)
	inner_color = rgba(0,0,0,0)
	font_color = $text
	fade_on_empty = false
	fade_timeout = 500
	rounding = 16
	check_color = $rgba(0,0,0,0)
	fail_color = $rgba(240,240,240,0)
	placeholder_text = <b>$USER: 0 | archlinux: $ATTEMPTS</b>
	valign = bottom
	halign = center
  position = 0, 35
}
label {
    monitor =
    text = cmd[update:60000] uptime -p | sed 's/up /󱎫  /' && echo &&echo '󰁹 ' $(cat /sys/class/power_supply/BAT0/capacity)%
    color = $green
    font_size = 12
    font_family = $font
    position = 30, 35
    halign = left
    valign = bottom
}

# Network status - bottom right
label {
    monitor =
    text = cmd[update:5000] timeout 1s bash -c 'if ping -c 1 -W 1 8.8.8.8 &>/dev/null; then echo "  Connected"; else echo "󰖪  Offline"; fi'
    color = $blue
    font_size = 12
    font_family = $font
    position = -30, 35
    halign = right
    valign = bottom
}

