# name: Rosé Pine Moon
# author: jishnurajendran
# upstream: https://github.com/jishnurajendran/hyprland-rosepine/blob/main/rose-pine-moon.conf
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist
$font           = Iosevka Regular
$base	        = 0xff2d353b
$surface        = 0xff343f44
$overlay        = 0xff3d484d
$muted          = 0xff475258
$subtle         = 0xff4a444e
$text           = 0xffd3c6aa
$red		= 0xffe67e80
$orange		= 0xffe69875
$yellow		= 0xffdbbc7f
$green		= 0xffa7c080
$aqua		= 0xff83c092
$blue		= 0xff7fbbb3
$purple		= 0xffd699b6
$highlightLow   = 0xff2a283e
$highlightMed   = 0xff4f585e
$highlightHigh  = 0xff56635f
$border		= 0xff859289
$select		= 0xffa7c080
$wallpaperLock  = /home/forest-terminal/Downloads/rocket-colorized.png
